# .github/workflows/build-bitcoin.yml
name: Build Bitcoin Core

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential libtool autotools-dev automake pkg-config \
            libevent-dev bsdmainutils libboost-system-dev libboost-filesystem-dev \
            libboost-test-dev libboost-thread-dev libminiupnpc-dev libzmq3-dev \
            libprotobuf-dev protobuf-compiler libqrencode-dev libsqlite3-dev

      - name: Build Bitcoin Core
        run: |
          ./autogen.sh
          ./configure
          make -j2
